name: Publish Python 🐍 distribution 📦 to PyPI and Bump Version

permissions:
  contents: write

on:
  push:
    branches:
      - release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Bump Patch Version
        run: poetry version patch

      - name: Get the new version
        id: vars
        run: echo "::set-output name=new_version::$(poetry version -s)"

      - name: Commit and Push the New Version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add pyproject.toml
          git commit -m "Bump version to ${{ steps.vars.outputs.new_version }}"
          git push

      - name: Build and publish
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry build
          poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
